### ISSUE TITLE
Bug ?!?

### ISSUE THREAD

**Issue by SebPautot** [Jinzulen/DEmojiJS#1]
` //Discord emoji
  if(message.content.startsWith(prefix+'d-emojiname')){
    message.delete(1000)
    var request = message.content.replace(prefix+'d-emojiname ', '')
  DEmojiJS.emojiByName(request).then(Emoji => {
    //try{
    message.channel.send(`${message.author} :`)
    message.channel.send(`${Emoji.image} \n \`\`\` ${Emoji.title} submitted by: ${Emoji.submitted_by}. \`\`\` `);
    //}catch(err){message.channel.send("Couldn't find any emoji")}
  }).catch(console.error)
  }
`
This is the code I use, it's coming from the website, just ma de few tweaks but Nothing really changed.

It is returning `TypeError: Cannot read property 'image' of undefined` through the console…
Do you have any idea ???

**Comment by SebPautot** [comment]
//Discord emoji
  if(message.content.startsWith(prefix+'d-emojiname')){
    message.delete(1000)
    var request = message.content.replace(prefix+'d-emojiname ', '')
  DEmojiJS.emojiByName(request).then(Emoji => {
    //try{
    message.channel.send(`${message.author} :`)
    message.channel.send(`${Emoji.image} \n \`\`\` ${Emoji.title} submitted by: ${Emoji.submitted_by}. \`\`\` `);
    //}catch(err){message.channel.send("Couldn't find any emoji")}
  }).catch(console.error)
  }

**Comment by SebPautot** [comment]
KappaYugi and Kappa are working, not the others on Discord Emoji website. Still testing things out rn.

**Comment by SebPautot** [comment]
Discord emoji is working, but wearycat, and every other emojis aren't working. wearycat is on the website's main page.

**Comment by SebPautot** [comment]
Ok, it looks like newest emotes cannot be used… ;-;

**Comment by SebPautot** [comment]
Emoji.image can't be used for emojis that are a bit far in popular, and all emoji beyond the limt. That's a big inconvenience.

**Comment by SebPautot** [comment]
Trying to fix this by not using the .image thing but it doesn't work

**Comment by Jinzulen** [comment]
Ah, I was wondering when someone would eventually come across this.

This is unfortunately a problem originating from Discord Emoji themselves, their API data can be incredibly outdated, at times lacking as much as 3 months worth of data (hence DEmojiJS failing to return any sort of data regarding newer emotes). I'm not sure if they have any plans to sort this out or if it's part of an intentional caching plan or something but it's out of my hands and seeing as DEmojiJS fetches data from the official API alone and doesn't scrape anything from the website, I'm afraid you will have to come up with your own work-around.

Alternatively, you could try writing to them about this and hoping that public concern regarding this would motivate them to do something about it.

**Comment by SebPautot** [comment]
Yes, all emojis with the /ID_TITLE on their URL format are not useable… the API doesn't give you their IDs because they can't find the name of it, so you can't "automate" it by doing `.../${Emoji.id}_${Emoji.title}`
 because of the API giving you an error. Only /TITLE can be used rn...

**Comment by Jinzulen** [comment]
Huh? That's not right, my friend. This issue has nothing to do with the slug ID of the emote (id_title), it's to do with the fact that their API literally has no record of the emote you're requesting. I know this because I ran more than my fair share of tests prior to releasing this wrapper.

This is irrelevant either way because this (outdated, horribly written) version of DEmojiJS has no mechanism by which to fetch an emote using its slug (unless you manually modify it to do otherwise), so all you need to submit is the title, this is of course by design to make it more convenient for anyone using it.
