### ISSUE TITLE
Not all emojis are available

### ISSUE THREAD

**Issue by ilyassesalama** [Jinzulen/DEmojiJS#10]
This API does not get all emojis available on emoji.gg.
If you check https://emoji.gg/api?request=stats you'll find that there are 26813, but the API shows only about +5400 emojis.

**Comment by King-BR** [comment]
First of all, this is just a wrapper for the official emoji.gg API.

Second of all, its emoji.gg fault since they don't provide all the emojis they have, (you would know that if you had read the README.md file, jinzulen explicitly says that the API doesn't provides all emojis)
![image](https://user-images.githubusercontent.com/51011050/107820216-2aa67100-6d59-11eb-854c-351dee371180.png)

If you dont believe it you can check at [this endpoint](https://emoji.gg/api/) which is supposed to provide all emoji from emoji.gg, but currently only +-6188 emojis are provided.

**Comment by ilyassesalama** [comment]
I know. I thought we might need to add another parameter that I may don't know about to fetch all emojis at once.

**Comment by Jinzulen** [comment]
I feel I have to clarify something, I am in **no way** associated with Emoji.gg and neither is this wrapper. I have only provided an unofficial third-party client for their API, that is where my part ends. I am not responsible for what the official API offers or doesn't offer, this is a problem with their API, not this wrapper. In other words, there is nothing I can do about it.

> I know. I thought we might need to add another parameter that I may don't know about to fetch all emojis at once.

There is nothing for either one of us to add because this is something that could only be tackled by Emoji.gg themselves.

You _could_ resort to the crude and inefficient _"solution"_ of scraping the website but I wouldn't recommend it for a myriad of reasons, the least of which is that it wouldn't actually give you what you want and chief among which is that you would easily get picked up by the anti DDOS protection as an attacker and get blocked, which is partly why I had to introduce a caching mechanism in the first place as I myself got shutdown multiple times while in the process of developing this tool.
